# fly.toml app configuration file generated for pathsix-backend on 2025-05-18T23:17:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pathsix-backend'
primary_region = 'dfw'

[build]
  builder = ""

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[autoscaling]
  min_machines_running = 1
  max_machines_running = 1
