"""Add contact_title and other fields

Revision ID: 136e6fd99586
Revises: 879bb020bae6
Create Date: 2025-06-02 00:53:55.274013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136e6fd99586'
down_revision: Union[str, None] = '879bb020bae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('contact_title', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('phone_label', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('secondary_phone', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('secondary_phone_label', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('contact_title', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('phone_label', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('secondary_phone', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('secondary_phone_label', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('lead_status', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('converted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'converted_on')
    op.drop_column('leads', 'lead_status')
    op.drop_column('leads', 'secondary_phone_label')
    op.drop_column('leads', 'secondary_phone')
    op.drop_column('leads', 'phone_label')
    op.drop_column('leads', 'contact_title')
    op.drop_column('clients', 'secondary_phone_label')
    op.drop_column('clients', 'secondary_phone')
    op.drop_column('clients', 'phone_label')
    op.drop_column('clients', 'contact_title')
    # ### end Alembic commands ###
