"""add_notes_to_projects_and_type_to_leads_clients

Revision ID: 3d3a8a80c9cb
Revises: 40b361a4ea8f
Create Date: 2025-06-22 22:24:22.858525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a8a80c9cb'
down_revision: Union[str, None] = '40b361a4ea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'notes')
    op.drop_column('leads', 'type')
    op.drop_column('clients', 'type')
    # ### end Alembic commands ###
