"""add contact fields to projects table

Revision ID: 6667a76887ac
Revises: d23a6a6e1afa
Create Date: 2025-06-29 20:39:32.111678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6667a76887ac'
down_revision: Union[str, None] = 'd23a6a6e1afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('primary_contact_name', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('primary_contact_title', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('primary_contact_email', sa.String(length=120), nullable=True))
    op.add_column('projects', sa.Column('primary_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('primary_contact_phone_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'primary_contact_phone_label')
    op.drop_column('projects', 'primary_contact_phone')
    op.drop_column('projects', 'primary_contact_email')
    op.drop_column('projects', 'primary_contact_title')
    op.drop_column('projects', 'primary_contact_name')
    # ### end Alembic commands ###
