"""add_project_interactions_and_user_preferences

Revision ID: d23a6a6e1afa
Revises: fd0285b4a2b2
Create Date: 2025-06-29 14:39:28.486507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23a6a6e1afa'
down_revision: Union[str, None] = 'fd0285b4a2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('preference_key', sa.String(length=100), nullable=False),
    sa.Column('preference_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'preference_key', name='uq_user_category_key')
    )
    op.create_index('idx_user_preferences_lookup', 'user_preferences', ['user_id', 'category', 'preference_key'], unique=False)
    op.create_index(op.f('ix_user_preferences_category'), 'user_preferences', ['category'], unique=False)
    op.create_index(op.f('ix_user_preferences_preference_key'), 'user_preferences', ['preference_key'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.add_column('interactions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interactions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'project_id')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_preference_key'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_category'), table_name='user_preferences')
    op.drop_index('idx_user_preferences_lookup', table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
